### ISSUE TITLE
Do not encode HTML entities in URLs

### ISSUE THREAD

**Issue by iagopiimenta** [premailer/premailer#193]
I would also like to add my voice to this issue. 
Currently I'm using premailer with [Liquid](https://github.com/Shopify/liquid) and need an alternative to ignore the contents of the src attribute.

This is the orignal link:

```
<a href="{{unsubscribe_link}}">Unsubscribe</a>
```

This is the current output:

```
<a href="%7B%7Bunsubscribe_link%7D%7D">Unsubscribe</a>
```

**Comment by stereoscott** [comment]
We use liquid, too. As a workaround, set your doctype at the start of your HTML so that the href attributes are not modified:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<body>
<a href="{{unsubscribe_link}}">Unsubscribe</a>
</body>
</html
```

In our case, this prevents the href attributes from being modified. It's also the recommended doctype for the most [email client compatibility](https://litmus.com/community/learning/13-foundations-email-coding-101).

**Comment by SirRawlins** [comment]
@stereoscott Almost two years on and your suggestion worked a charm for me. Thanks.

**Comment by akzhan** [comment]
Solution is https://github.com/premailer/premailer/issues/193#issuecomment-97645998

**Comment by theroch** [comment]
My previous version with (3.2.10.20170806-1) doesn't work correctly.
But with the current Nightly (3.2.10.20170830-1) the URLs are displayed correctly.

**Comment by flux627** [comment]
The solution by @stereoscott is not working as of right now.

**Comment by danhart** [comment]
Agree with @flux627, @stereoscott's this solution is no longer working.

**Comment by foxyblocks** [comment]
This seems to be an ongoing issue. Is there any fix?

**Comment by danseaman6** [comment]
Can this be re-opened? the previously mentioned comment is not a  fix and [downgrading the doctype is not recommended](https://www.emailonacid.com/blog/article/email-development/doctype_-_the_black_sheep_of_html_email_design/). This bug still exists.

**Comment by brakai295** [comment]
Same here. I'd like to use `{{ }}` in URLs but the above solution doesn't seem to work anymore.

**Comment by stereoscott** [comment]
Not sure if others are still running into this, but I wanted to share an updated workaround.

The root of this issue is that nokogiri will escape special characters from href attributes. If your `href` attribute contains a liquid placeholder like `<a href="{{ unsubscribe_link }}">`, after premailer is done with it, those placeholders turn into `<a href="{{%20deal_url%20}}">`. 

Our fix is to run our HTML template through premailer first, then swap out any escaped characters that are part of liquid tags before parsing the template to liquid:

```
template = premailer(html_template).to_inline_css
# nokogiri will escape our liquid tags if they are in an href attribute
subs = {
  '{{%20' => '{{ ',
  '%20}}'  => ' }}',
}.freeze
template.gsub!(Regexp.union(subs.keys), subs)
```

If your templates contain control flow tags, the easiest way we found to avoid having those tags modified is to put them in HTML comments:

```
<p><!--{% if 1 > 0 %}-->This works<!--{% endif %}--></p>
```
The content inside the comments isn't modified by premailer, so the control flow tags remain intact for Liquid.


P.S. This is very random but @brakai295 you and I met up IRL in NYC for coffee w/ Darren back in 2009!

**Comment by GregOriol** [comment]
This issue should be reopened, it's still active and causing problems
