### ISSUE TITLE
css shorthand declarations can cause issues

### ISSUE THREAD

**Issue by rafeca** [premailer/premailer#211]
Given the following input html:

``` html
<html lang="en">
<head>
  <style type="text/css">
    body { background-color: #ccc; }
  </style>
  <style data-premailer="ignore" type="text/css">
    @media only screen and (max-width: 580px) {
      body {
        background-image: url(http://lorempixel.com/400/200/cats/);
      }
    }
  </style>
</head>
<body></body>
</html>
```

I would expect that the parsed html would be displayed as the input... however, as the `background-color` rule gets shortened to `background`, the parsed html never displays the background image.

**Note**: This is actually an issue of `css_parser` and I've already created a [pull request there](https://github.com/premailer/css_parser/pull/53), this issue only shows why that PR is needed.

**Comment by aarenhofferth** [comment]
What ever happened to this? This is pretty important to email compatibility.

**Comment by kgrote** [comment]
I'm having issues with this too. Outlook.com won't display the background color the way Premailer parses it. Not sure if it's because of the `background` shorthand property or not using hexadecimal colors, or both. Either way it's not good practice for Premailer to keep doing it the way it is. Premailer should output as `style="background-color: #ffffff; background-image: url(/path/to/image);"`

**Comment by foreachlt** [comment]
I've recently had an issue with border shorthands. I've proposed a fix: https://github.com/premailer/css_parser/pull/58 here.

**Comment by tcwalther** [comment]
I just ran into the same issue, where a single `background-color: ` declaration gets shortened to `background: ` and then doesn't work in Outlook anymore.

**Comment by akzhan** [comment]
Both pull request merged a time ago. Thanks to all contributors!
