### ISSUE TITLE
Use nokogiri by default

### ISSUE THREAD

**Issue by bogdan** [premailer/premailer#257]
Why premailer still uses deprecated hpricot by default? Can we just get done with it or at least use nokogiri by default?

**Comment by akzhan** [comment]
Just 1.8 is reason

**Comment by bogdan** [comment]
Does 1.8 has bugs on nokogiri so it can present but not work?
It can be fixed anyway by checking ruby version as well. We don't want to get hurt on 2.2 because 0.1% of people still using 1.8.

**Comment by ericdfields** [comment]
For now, I need hpricot in my Rails app's Gemfile as another dependency. I'd like to force Premailer to use nokogiri because hpricot isn't parsing my test emails correctly. I'm using the premailer-rails gem and setting the adapter to nokogiri there, but it seems as if the mere presence of hpricot in your gemfile.lock makes Premailer use it. Any way to get around this? Thanks.

**Comment by akzhan** [comment]
Done
