### ISSUE TITLE
Premailer returns <title/> for empty document title

### ISSUE THREAD

**Issue by neurospeech** [premailer/premailer#330]
Chrome and other browsers break HTML as `TITLE` is not allowed as empty tag. So it displays empty html. I don't know if this bug is due to AngleSharp's wrong html specs implementation or anything done in your library.

Alternative is I manually set Document.Title = "non-empty-string", for html to generate correctly.

**Comment by samfromlv** [comment]
We have the same issue with empty title tags with PreMailer 1.5.5 and AngeSharp 0.9.9. It seems that other tags are also broken, for example <div></div> becomes <div/> after call to PreMailer.MoveCssInline(html, true). It seems this is critical issue because this html is invalid and for example Gmail shows emails with <title/> as empty.

We successfully fixed the issue by rolling back PreMailer to version 1.5.4 and AngleSharp to 0.9.5.

**Comment by akzhan** [comment]
Please set non empty title.

I will check to remove empty titles later.

**Comment by akzhan** [comment]
Looks like wrong repository. Please create issue at https://github.com/milkshakesoftware/PreMailer.Net
