### ISSUE TITLE
Option to ignore Django | Jinja syntax

### ISSUE THREAD

**Issue by msert29** [premailer/premailer#461]
I wanted to use premailer to compile my email templates however it seems that there are no options to ignore Jinja or Django syntax.

As an example 

```
{% if user.age > 18 %}
....
```

Gets compiled into this

```{% if user.age &gt; 1 %}```

Wondering if there is scope to add an option to completely ignore django and jinja syntax?

**Comment by grosser** [comment]
there is no support for their syntax, I think this happens when sending things through nokogiri,
to debug you can place a bunch of `p` throughout the gem and see where it gets broken
pr welcome, it should not touch things like that
(also fyi this is a ruby gem, so you might be in the wrong place unless you are using ruby with Django)
